<?php
/** @var $this SlideTwo */

use ProtectedNet\FrontendTest\Components\Button\Button;
use ProtectedNet\FrontendTest\Partials\HeroContent\SlideTwo\SlideTwo;

?>


<div class="<?= $this->getElementName('background-img') ?>" style="background-image: url('<?= $this->getImg('slider-2.jpg') ?>');"></div>


<div class="<?= $this->getElementName('content') ?>">
  <div class="grid-container">
    <div class="grid-x">
      <div class="cell">
        <h1 class="<?= $this->getElementName('title') ?>">Staffing <strong>solutions</strong> for you</h1>
      </div>
    </div>

    <div class="grid-x grid-padding-y grid-padding-x <?= $this->getElementName('cta-holder') ?>">
      <div class="cell medium-offset-1 medium-5 text-center medium-text-right">
        <?= Button::i('Search a Job')->iconRight("<i class='fa fa-chevron-right'></i>") ?>
      </div>
      <div class="cell medium-5 end text-center medium-text-left">
        <?= Button::i('Post a Resume')->iconRight("<i class='fa fa-chevron-right'></i>") ?>
      </div>
    </div>
  </div>
</div>
