<?php
/** @var $this FeatureCard */
use ProtectedNet\FrontendTest\Components\FeatureCard\FeatureCard;
?>

<?php if($this->getIcon()): ?>
  <div class="<?= $this->getElementName('icon') ?>">
    <?= $this->getIcon()->produceSafeHTML() ?>
  </div>
<?php endif; ?>

<div class="<?= $this->getElementName('content') ?>">

  <?php if($this->getTitle()): ?>
    <h4 class="feature-card__title"><?= $this->getTitle() ?></h4>
  <?php endif; ?>

  <?php if($this->getSubtitle()): ?>
    <h5 class="feature-card__subtitle"><?= $this->getSubtitle() ?></h5>
  <?php endif; ?>

  <?php if($this->getDescription()): ?>
    <p class="feature-card__description"><?= $this->getDescription() ?></p>
  <?php endif; ?>

</div>
