#!/usr/bin/env php
<?php
$loader = require_once('vendor/autoload.php');
$cubex = new Cubex\Cubex(__DIR__, $loader);
$project = new \ProtectedNet\FrontendTest\FrontendTestSite($cubex);
exit($cubex->cli());
