<?php
/** @var $this Nav */

use ProtectedNet\FrontendTest\Components\Nav\Nav;

?>

<div class="grid-container">
  <div class="grid-x">
    <div class="cell small-3">
      <img src="<?= $this->getImg('logo.png') ?>" alt="our logo" class="<?= $this->getElementName('logo') ?>" />
    </div>
    <div class="cell small-9">

      <a trigger class="<?= $this->getElementName('burger-menu') ?>">
        <span></span>
        <span></span>
        <span></span>
      </a>

      <ul class="<?= $this->getElementName('list') ?>">
        <?php foreach($this->getNavItems() as $key => $navItem): ?>
          <li class="<?= $this->getElementName('list', 'item') ?>">
            <?= $navItem->addClass($this->getElementName('cta')) ?>
          </li>
        <?php endforeach; ?>
      </ul>
    </div>
  </div>
</div>
